# Log files location
property.basePath=test-outputs/Logs

# Define file appender
appender.file.type=File
appender.file.name=fileAppender
appender.file.fileName=${basePath}/application.log
appender.file.layout.type=PatternLayout
appender.file.layout.disableAnsi=false
appender.file.filter.threshold.type=ThresholdFilter
appender.file.filter.threshold.level=debug
appender.file.layout.pattern=[%p] - [%d{dd-MM-yyyy HH:mm:ss}] [%t] [%c] - %msg%n

#Define stdout (console) appender
appender.console.type=Console
appender.console.name=consoleAppender
appender.console.layout.type=PatternLayout
appender.console.layout.disableAnsi=false
appender.console.filter.threshold.type=ThresholdFilter
appender.console.filter.threshold.level=debug
appender.console.layout.pattern=%highlight{[%p] - [%d{dd-MM-yyyy HH:mm:ss}] [%t] [%c] - %msg}{FATAL=red, ERROR=red, WARN=yellow, INFO=blue, DEBUG=green bold, TRACE=black}%n

# Configure root logger
rootLogger=debug, fileAppender, consoleAppender
rootLogger.level=debug